version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: always
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - SERVER_IP=${SERVER_IP}
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - .:/src
